language: objective-c

env:
 matrix:
  - MONO_VERSION="3.2.4"

before_install:
 - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
 - sudo gem install bundler
 - bundle install
 - rake install

script:
 - rake test

notifications:
  email: false
